name = "PolyDAQP"
uuid = "be5c70c9-e47a-4559-82a9-cba980583202"
authors = ["Daniel Arnstr√∂m <daniel.arnstrom@liu.se>"]
version = "0.3.0"

[deps]
DAQP = "c47d62df-3981-49c8-9651-128b1cd08617"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
DAQP = "0.6.0"
PGFPlotsX = "1.5.0"
RecipesBase = "1.3.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
